name = "nptel-telegram-bot"
main = "src/index.ts"
compatibility_date = "2026-05-11"

[[kv_namespaces]]
binding = "KV"
id = "8218b16c96a54ee583b7955f83266db7"

[[services]]
binding = "BACKEND"
service = "nptel-notifier-backend"

[observability.logs]
enabled = false
invocation_logs = true

[observability.traces]
enabled = false
