name = "nptel-notifier-backend"
main = "src/index.ts"
compatibility_date = "2026-05-11"

[observability.logs]
enabled = false
invocation_logs = true

[observability.traces]
enabled = false

[[d1_databases]]
binding = "DB"
database_name = "nptel-notifier"
database_id = "a5b23053-be8e-40b3-9934-be4eb63a8cee"
migrations_dir = "migrations"

[triggers]
crons = ["*/30 * * * *"]
